[Bot]

token = ""
guild = 0
chat = 0

# Experimental and unstable features.
# USE AT YOUR OWN RISK!!!
[Experimental]
    [Experimental.Discord]
    enabled = false
    allowOfflinePlayers = false
    requiredRoles = []
    loginByIp = false
