token = ""
channel = 0

[Minecraft]

messageFormat = "{sender} » {message}"
replyFormat = "<gray>(Replying to @{sender} » <hover:'{message}'>{summary}</hover>)</gray>"
summaryMaxLength = 20

coloredRoles = true

appendImages = true
imageMaxWidth = 60
imageMaxHeight = 30

[Discord]

playerAvatarUrl = "https://cravatar.eu/helmavatar/{player}/256"

joinMessages = [
    "### :wave:   {player} joined the game"
]
leaveMessages = [
    "### :door:   {player} left the game"
]
deathMessages = [
    "### :skull_crossbones:   {death_message}"
]

advancementMessages = [
    "### :dart:   {player} has made the advancement {advancement_name}",
    "{advancement_description}"
]
goalMessages = [
    "### :dart:   {player} has reached the goal {advancement_name}",
    "{advancement_description}"
]
challengeMessages = [
    "### :dart:   {player} has completed the challenge {advancement_name}",
    "{advancement_description}"
]

startMessage = "### :white_check_mark:   Server started"
stopMessage = "### :octagonal_sign:   Server stopped"
