[versions]

minecraft = "26.2"

fabric-loader = "0.19.3"
fabric-kotlin = "1.13.13+kotlin.2.4.10"
fabric-api = "0.156.0+26.2"

kordex="2.5.0-SNAPSHOT"

fabric-loom = "1.17-SNAPSHOT"
kotlin = "2.4.10"

[libraries]

minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

kordex = { module = "dev.kordex:kord-extensions", version.ref = "kordex" }

[plugins]

fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }